#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --set-zoom-fill ~/Wall/base.png &
picom -f --experimental-backend &
dunst &
~/.config/polybar/launch.sh --docky &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
xdotool key XF86MonBrightnessUp
xdotool key XF86MonBrightnessDown

bspc config focused_border_color "#BD93F9"
